FROM quay.io/ramalama/ramalama:latest

RUN dnf install -y curl --nodocs && dnf clean all

EXPOSE 8080

ENTRYPOINT ["ramalama", "serve", "--port", "8080", "--ctx-size", "4096", "ollama://llama3.2:3b"]
